In [103]:
#import Packages for our model
import tensorflow as tf

In [104]:
import numpy as np
import pandas as pd
#import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [105]:
from tensorflow.keras import layers, datasets, models
from tensorflow.keras.utils import to_categorical

In [111]:
#importing dataset
data=pd.read_csv('/content/penguins.csv')

In [112]:
data

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex  \
0              39.1           18.7              181.0       3750.0    male   
1              39.5           17.4              186.0       3800.0  female   
2              40.3           18.0              195.0       3250.0  female   
3               NaN            NaN                NaN          NaN     NaN   
4              36.7           19.3              193.0       3450.0  female   
..              ...            ...                ...          ...     ...   
339            55.8           19.8              207.0       4000.0    male   
340            43.5           18.1              202.0       3400.0  female   
341            49.6           18.2              193.0       3775.0    male   
342            50.8           19.0              210.0       4100.0    male   
343            50.2           18.7              198.0       3775.0  female   

       species     island  
0       Adelie  Torgersen  
1       Adelie  Torgersen  
2       Adelie  Torgersen  
3       Adelie  Torgersen  
4       Adelie  Torgersen  
..         ...        ...  
339  Chinstrap      Dream  
340  Chinstrap      Dream  
341  Chinstrap      Dream  
342  Chinstrap      Dream  
343  Chinstrap      Dream  

[344 rows x 7 columns]

In [113]:
# Drop rows with missing values
data.dropna(inplace=True)

In [114]:
# Fill missing values with the mean
data.fillna(data.mean(), inplace=True)

<ipython-input-114-d9766fc39081>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.fillna(data.mean(), inplace=True)


In [115]:
data

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g     sex  \
0              39.1           18.7              181.0       3750.0    male   
1              39.5           17.4              186.0       3800.0  female   
2              40.3           18.0              195.0       3250.0  female   
4              36.7           19.3              193.0       3450.0  female   
5              39.3           20.6              190.0       3650.0    male   
..              ...            ...                ...          ...     ...   
339            55.8           19.8              207.0       4000.0    male   
340            43.5           18.1              202.0       3400.0  female   
341            49.6           18.2              193.0       3775.0    male   
342            50.8           19.0              210.0       4100.0    male   
343            50.2           18.7              198.0       3775.0  female   

       species     island  
0       Adelie  Torgersen  
1       Adelie  Torgersen  
2       Adelie  Torgersen  
4       Adelie  Torgersen  
5       Adelie  Torgersen  
..         ...        ...  
339  Chinstrap      Dream  
340  Chinstrap      Dream  
341  Chinstrap      Dream  
342  Chinstrap      Dream  
343  Chinstrap      Dream  

[333 rows x 7 columns]

In [116]:
# Save the cleaned dataset
data.to_csv('cleaned_penguins.csv', index=False)

In [117]:
#Encode the species
data['species'].replace(to_replace={
    "Adelie":0,
    "Gentoo":1,
    "Chinstrap":2,
}, inplace = True)

In [118]:
#Encode the islan
data['island'].replace(to_replace={
    "Torgersen":0,
    "Biscoe":1,
    "Dream":2,
}, inplace = True)

In [119]:
#Encode the sex
data['sex'].replace(to_replace={
    "female":0,
    "male":1,
}, inplace = True)

In [120]:
#identify inputs and outputs
x = data.iloc[:, 0:4].values
y = data.iloc[:, 4:7].values

In [121]:
print(x[0:5])

[[  39.1   18.7  181.  3750. ]
 [  39.5   17.4  186.  3800. ]
 [  40.3   18.   195.  3250. ]
 [  36.7   19.3  193.  3450. ]
 [  39.3   20.6  190.  3650. ]]


In [123]:
#Encoded y values
print(y[0:5])

[[1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]]


In [124]:
print(x.shape)
print(y.shape)

(333, 4)
(333, 3)


In [125]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)


In [126]:
#create model
model = tf.keras.Sequential ([
    #layers 01
    tf.keras.layers.Dense(10, activation ='relu'),
    #layers 02
    tf.keras.layers.Dense(10, activation ='relu'),
    #layers 03
    tf.keras.layers.Dense(3, activation ='softmax')
    ])
model

In [127]:
#compiling the model
model.compile(optimizer= 'rmsprop',
              loss='categorical_crossentropy',
              metrics = ['accuracy'])

In [128]:
#training the model
model.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
27/27 [==============================] - 1s 2ms/step - loss: 690.6606 - accuracy: 0.4098
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 485.7840 - accuracy: 0.4098
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 260.9843 - accuracy: 0.4286
Epoch 4/100
27/27 [==============================] - 0s 2ms/step - loss: 64.9486 - accuracy: 0.3872
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: 8.2504 - accuracy: 0.3647
Epoch 6/100
27/27 [==============================] - 0s 2ms/step - loss: 7.7777 - accuracy: 0.3534
Epoch 7/100
27/27 [==============================] - 0s 2ms/step - loss: 8.1096 - accuracy: 0.3684
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: 8.5813 - accuracy: 0.3571
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 8.9498 - accuracy: 0.3647
Epoch 10/100
27/27 [==============================] - 0s 2ms/step - loss: 8.3307 - accuracy: 0.3496
Ep

In [129]:
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print('Test Accuracy:', accuracy )
print('Test Loss:', loss)

Test Accuracy: 0.46268656849861145
Test Loss: 125.0089340209961


In [130]:
#see predictesd data
y_pred = model.predict(x_test)
y_pred

3/3 [==============================] - 0s 5ms/step


array([[0.9324533 , 0.        , 0.06754669],
       [0.8872046 , 0.        , 0.11279541],
       [0.9840936 , 0.        , 0.01590639],
       [0.96036124, 0.        , 0.03963884],
       [0.96036124, 0.        , 0.03963884],
       [0.95531917, 0.        , 0.04468087],
       [0.9688562 , 0.        , 0.03114383],
       [0.98087597, 0.        , 0.01912404],
       [0.96036124, 0.        , 0.03963884],
       [0.9626731 , 0.        , 0.03732689],
       [0.96978533, 0.        , 0.03021459],
       [0.9465967 , 0.        , 0.05340333],
       [0.79818684, 0.        , 0.20181324],
       [0.9324533 , 0.        , 0.06754669],
       [0.95257413, 0.        , 0.04742588],
       [0.9099069 , 0.        , 0.09009299],
       [0.95531917, 0.        , 0.04468087],
       [0.89029425, 0.        , 0.10970578],
       [0.96485513, 0.        , 0.03514485],
       [0.9099069 , 0.        , 0.09009299],
       [0.8774767 , 0.        , 0.1225232 ],
       [0.91964257, 0.        , 0.08035747],
       [0.

In [131]:
#compare actual outputs and preditded outputs
actual = np.argmax(y_test, axis = 1)
predicted = np.argmax(y_pred, axis = 1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 2 1 0 0 0 0 1 0 0 1 0 2 1 2 2 1 0 0 2 0 2 1 1 1 0 0 2 2 0 0 0 2 0 2 1 1
 2 1 0 1 1 0 0 0 0 0 2 0 0 1 0 0 1 2 2 2 0 2 1 0 0 0 1 2 2 0]
Predicted: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
